name: Non OMV tests

on:
  push:
    branches: [ master, development, test* ]
  pull_request:
    branches: [ master, development, test* ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12" ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Install OMV
      run: |
        pip install git+https://github.com/OpenSourceBrain/osb-model-validation
        pip install scipy sympy matplotlib cython pandas tables

        pip install setuptools
      

    - name: Install OSB API
      run: |
        git clone https://github.com/OpenSourceBrain/OSB_API.git
        cd OSB_API/python
        python setup.py install

    - name: Test Channelpedia related scripts
      run: |
        cd Channelpedia
        pip install pyneuroml
        pip install pyelectro
        python ChannelpediaToNeuroML2.py HCN1
        python analyse.py
        pynml LEMS_Test_HCN1.xml -nogui

    - name: Test NMC related scripts
      run: |
        omv install NEURON
        pip install jinja2
        cd NMC/parser
        nrnivmodl ../NEURON/ # compile mod files for use here; nrnivmodl installed with Neuron via pip
        python ParseAll.py
        ls -alt ../NeuroML2/
        omv list -V
